version: "3.3"

services:

  server:
    container_name: flag_warehouse
    build: 
      context: .
    ports:
      - 5555:5555
    volumes:
      - ./config.py:/server/config.py:ro
      - ./instance:/server/instance/
